name: CI/CD pipeline

on: # Les déclencheurs
  push:
    branches: 
    - main
    - develop
    - 'feature/**'
    - 'fix/**'
    - 'release/**'
    - 'hotfix/**'

  pull_request:
    branches:
    - main
    - develop


jobs: # Les actions
  test-and-build:
      name: Tests & Build             
      runs-on: ubuntu-latest           

      steps:
        - name: Checkout code
          uses: actions/checkout@v4    
        
        - name: Setup Node.js
          uses: actions/setup-node@v4  
          with:
            node-version: '20'   
            cache: 'npm'     
        
        # Frontend
        - name: Install Frontend
          working-directory: ./frontend  
          run: npm ci                    
        
        - name: Lint Frontend
          working-directory: ./frontend
          run: npm run lint     

        - name: Test Frontend
          working-directory: ./frontend   
          run: npm test         
        
        - name: Build Frontend
          working-directory: ./frontend
          run: npm run build       
